name: Build BusyBox for Android 64-bit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip build-essential git

      - name: Download BusyBox 1.36.1 source code
        run: |
          wget https://busybox.net/downloads/busybox-1.36.1.tar.bz2 -P /tmp
          tar -xjf /tmp/busybox-1.36.1.tar.bz2 -C $HOME
          cd $HOME/busybox-1.36.1

      - name: Install Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -P /tmp
          unzip /tmp/android-ndk-r25b-linux.zip -d $HOME
          export ANDROID_NDK_HOME=$HOME/android-ndk-r25b
          export PATH=$ANDROID_NDK_HOME:$PATH

      - name: Set up the cross-compiler for ARM64
        run: |
          export CROSS_COMPILE=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-
          export AR=${CROSS_COMPILE}ar
          export AS=${CROSS_COMPILE}as
          export LD=${CROSS_COMPILE}ld
          export CC=${CROSS_COMPILE}gcc
          export CXX=${CROSS_COMPILE}g++
          export STRIP=${CROSS_COMPILE}strip
          export NM=${CROSS_COMPILE}nm
          export RANLIB=${CROSS_COMPILE}ranlib
          export OBJCOPY=${CROSS_COMPILE}objcopy

      - name: Compile BusyBox for Android 64-bit
        run: |
          cd $HOME/busybox-1.36.1
          make defconfig
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-android-

      - name: Archive build output
        run: |
          cd $HOME/busybox-1.36.1
          mkdir -p $GITHUB_WORKSPACE/output
          cp busybox $GITHUB_WORKSPACE/output/busybox-arm64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: busybox-arm64
          path: $GITHUB_WORKSPACE/output/busybox-arm64
