name: Build Telnet and FTP Server Binaries for Android 64-bit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 11 (using temurin)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      # Set up Android SDK using android-actions/setup-android
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '30.0.3'
          ndk-version: '23.1.7779620'

      # Install CMake, Android NDK, and other dependencies
      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build clang gcc

      # Set up Android NDK (for native C/C++ compilation)
      - name: Set up Android NDK
        run: |
          mkdir -p $HOME/android-ndk
          wget https://dl.google.com/android/repository/android-ndk-r23b-linux.zip -P $HOME/android-ndk
          unzip $HOME/android-ndk/android-ndk-r23b-linux.zip -d $HOME/android-ndk

      # Configure the build environment for Android 64-bit architecture
      - name: Configure build environment
        run: |
          export ANDROID_NDK=$HOME/android-ndk/android-ndk-r23b
          export PATH=$ANDROID_NDK:$PATH
          export SYSROOT=$ANDROID_NDK/platforms/android-21/arch-arm64
          export TOOLCHAIN=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64
          export CC=$TOOLCHAIN/bin/aarch64-linux-android21-clang
          export CXX=$TOOLCHAIN/bin/aarch64-linux-android21-clang++

      # Build the Telnet Server binary for Android 64-bit
      - name: Build Telnet Server binary
        run: |
          cd path/to/telnet-server
          mkdir -p build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_NATIVE_API_LEVEL=21
          cmake --build .

      # Build the FTP Server binary for Android 64-bit
      - name: Build FTP Server binary
        run: |
          cd path/to/ftp-server
          mkdir -p build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_NATIVE_API_LEVEL=21
          cmake --build .

      # Upload generated binaries as artifacts
      - name: Upload generated binaries
        uses: actions/upload-artifact@v3
        with:
          name: server-binaries
          path: |
            path/to/telnet-server/build/telnet-server-binary
            path/to/ftp-server/build/ftp-server-binary
